#print("Мене звуть", "Пайтон.", end="")
#print("Монті Пайтон")

#print("Мене", "звати", sep="_", end="*")
#print("Монті", "Пайтон.", sep="*", end="*\n")

#print("Основи","Програмування","в", sep="***", end="...")
#print("Python")

# print("    *")
# print("   * *")
# print("  *   *")
# print(" *     *")
# print("***   ***")
# print("  *   *")
# print("  *   *")
# print("  *****")


# print("більше:")
# ###################
# print("        *")
# print("       * *")
# print("      *   *")
# print("     *     *")
# print("    *       *")
# print("   *         *")
# print("  *           *")
# print(" *             *")
# print("******     ******")
# print("     *     *")
# print("     *     *")
# print("     *     *")
# print("     *     *")
# print("     *     *")
# print("     *     *")
# print("     *******")
###################

# print("двічі:")
###################
# print("        *        "*2)
# print("       * *       "*2)
# print("      *   *      "*2)
# print("     *     *     "*2)
# print("    *       *    "*2)
# print("   *         *   "*2)
# print("  *           *  "*2)
# print(" *             * "*2)
# print("******     ******"*2)
# print("     *     *     "*2)
# print("     *     *     "*2)
# print("     *     *     "*2)
# print("     *     *     "*2)
# print("     *     *     "*2)
# print("     *     *     "*2)
# print("     *******     "*2)
